services:
  api:
    build:
      context: .
      dockerfile: HikeConnect.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Cors__AllowedOrigins__0: http://hikeconnect.spoons.su:9011
      Cors__AllowedOrigins__1: https://hikeconnect.spoons.su
    restart: unless-stopped

  webapp:
    build:
      context: .
      dockerfile: HikeConnect.WebApp/Dockerfile
    expose:
      - "9011:7029"
    depends_on:
      - api
    restart: unless-stopped
